### ISSUE TITLE
generate_mesh broken with changes to meshio.Mesh.cell_data

### ISSUE THREAD

**Issue by gdmcbain** [nschloe/pygmsh#297]
nschloe/meshio#631 changed `meshio.Mesh.cell_data` from a `dict` to a `list`.  That means that something like (adapted from scikit-fem [ex12.py](https://github.com/kinnala/scikit-fem/blob/c8261575ba5295030161fe967776499b019a7cd8/docs/examples/ex12.py#L7-L14))
```python
from pygmsh import generate_mesh
from pygmsh.built_in import Geometry

geom = Geometry()
circle = geom.add_circle([0.] * 3, 1., .5**3)
geom.add_physical(circle.line_loop.lines, 'circle')
geom.add_physical(circle.plane_surface, 'disk')
mesh = generate_mesh(geom, dim=2)
print(mesh)
```
fails at `generate_mesh` with
```
…
  File "/home/geordie/src/meshio/meshio/gmsh/_gmsh41.py", line 224, in _read_elements
    cell_data["gmsh:physical"].append(
AttributeError: 'dict' object has no attribute 'append'
```

I think this should involve a simple change here which I'll look into.

**Comment by gdmcbain** [comment]
Actually the error is in `meshio.read` (inside `generate_mesh`) so it needs fixing over there.

**Comment by gdmcbain** [comment]
The problem in nschloe/meshio#644 is fixed by nschloe/meshio#645 but then that uncovers another error here:
```
  File "/home/geordie/src/pygmsh/pygmsh/helpers.py", line 165, in generate_mesh
    ncells = numpy.concatenate([numpy.concatenate(c) for c in mesh.cells.values()])
AttributeError: 'list' object has no attribute 'values'
```

**Comment by gdmcbain** [comment]
This works with pygmsh 6.0.4 and meshio 4.0.1 (or rather the current master branch in each case).
